on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all

      - run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VERSION=$(npm version patch --git-tag-version=false)
          git add package.json package-lock.json
          git commit -m "Bump version to $VERSION"
          git push origin master

          git checkout -b release/$VERSION
          git add dist -f
          git commit -m "Release $VERSION"
          git tag $VERSION
          git push origin release/$VERSION --tags
